[remote]
privkey = "${HOME}/.ssh/id_rsa"
tv_dir = "/home/osmc/rusttv-sandbox/"
#tv_dir = "/usr/store/tv/"

[local]
default_dir = "${HOME}/.rusttv/sandbox/"
#default_dir = "${HOME}/tv/"

[validation]
allowed_exts = ["avi", "m4v", "ass", "3gp", "mkv", "mp4", "srt"]
on_failure = "skip"
