[remote]
host = "rusttv"
privkey = "${HOME}/.ssh/id_rsa"
tv_dir = "/home/osmc/rusttv-sandbox/"

[local]
tv_dir = "${HOME}/.rusttv/sandbox/"

[validation]
allowed_exts = ["avi", "m4v", "ass", "3gp", "mkv", "mp4", "srt"]
on_failure = "skip"
prompt_confirmation = true

[validation.tmdb]
enabled = true
token = "${TMDB_ACCESS_TOKEN}"

[ui]
block_closing = true

[osmc]
enable_refresh = true
host = "rusttv"
protocol = "http"
prefix = "/"
username = "osmc"
password = "osmc"

