name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install windows target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build and test
        run: make clean build/cross test
        env:
          TERM: xterm-256color
